In [3]:
import numpy as np# the alias for numpy is np

In [4]:
mylist=[1,2,3,4]
arr=np.array(mylist)#converting a list into a array

In [5]:
type(arr)#display the type of a variable
arr.shape#check the number of dimensions

(4,)

In [6]:
#creating a multidimensional array from a list
mylist1=[2,3,4,5]
mylist2=[3,4,5,6]
mylist3=[4,5,6,7]
arr=np.array([mylist1,mylist2,mylist3])#combining three lists into one multidimensional array
arr

array([[2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7]])

In [7]:
arr.shape#there rows four columns

(3, 4)

In [8]:
#changing the dimensions of the numpy array
arr.reshape(1,12)#the total number of elements should remain the same
arr

array([[2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7]])

In [9]:
arr[0:3,0:3]

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [10]:
arr=np.arange(0,10,step=2)#step gap of 2 until it reaches 10
arr

array([0, 2, 4, 6, 8])

In [11]:
np.linspace(1,10,50)#50 equidistant points between 1 to 10

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [12]:
a=arr

In [13]:
a[1:]=12#from the 1st index till the last index replace with 12
arr

array([ 0, 12, 12, 12, 12])

In [14]:
arr3=arr.copy()#shallow copy
arr3

array([ 0, 12, 12, 12, 12])

In [15]:
arr3[3]=20#the modifications will be made on a copy of the arr3 and not on the arr variable
arr

array([ 0, 12, 12, 12, 12])

In [16]:
mylist1=[2,3,4,5]
mylist2=[3,4,5,6]
mylist3=[4,5,6,7]
arr=np.array([mylist1,mylist2,mylist3])#combining three lists into one multidimensional array
arr

array([[2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7]])

In [17]:
arr>6

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True]])

In [18]:
arr3.reshape(1,5)
arr3

array([ 0, 12, 12, 20, 12])

In [19]:
val=2
arr*20

array([[ 40,  60,  80, 100],
       [ 60,  80, 100, 120],
       [ 80, 100, 120, 140]])

In [22]:
val=2
arr[arr<300]#prints all elements below 300

array([2, 3, 4, 5, 3, 4, 5, 6, 4, 5, 6, 7])

In [26]:
np.ones((2,5),dtype=int)#by default dtype=float

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [27]:
np.random.rand(3,3)#construct a 3X3 matrix having random numbers

array([[0.72117311, 0.74873207, 0.98920546],
       [0.6922987 , 0.03331098, 0.86788345],
       [0.72021214, 0.31558486, 0.1043308 ]])