In [30]:
from google.colab import files
files.upload()

Saving iris.csv to iris (2).csv


{'iris (2).csv': b'sepal-length,sepal-width,petal-length,petal-width,species\r\n5.1,3.5,1.4,0.2,Setosa\r\n4.9,3,1.4,0.2,Setosa\r\n4.7,3.2,1.3,0.2,Setosa\r\n4.6,3.1,1.5,0.2,Setosa\r\n5,3.6,1.4,0.2,Setosa\r\n5.4,3.9,1.7,0.4,Setosa\r\n4.6,3.4,1.4,0.3,Setosa\r\n5,3.4,1.5,0.2,Setosa\r\n4.4,2.9,1.4,0.2,Setosa\r\n4.9,3.1,1.5,0.1,Setosa\r\n5.4,3.7,1.5,0.2,Setosa\r\n4.8,3.4,1.6,0.2,Setosa\r\n4.8,3,1.4,0.1,Setosa\r\n4.3,3,1.1,0.1,Setosa\r\n5.8,4,1.2,0.2,Setosa\r\n5.7,4.4,1.5,0.4,Setosa\r\n5.4,3.9,1.3,0.4,Setosa\r\n5.1,3.5,1.4,0.3,Setosa\r\n5.7,3.8,1.7,0.3,Setosa\r\n5.1,3.8,1.5,0.3,Setosa\r\n5.4,3.4,1.7,0.2,Setosa\r\n5.1,3.7,1.5,0.4,Setosa\r\n4.6,3.6,1,0.2,Setosa\r\n5.1,3.3,1.7,0.5,Setosa\r\n4.8,3.4,1.9,0.2,Setosa\r\n5,3,1.6,0.2,Setosa\r\n5,3.4,1.6,0.4,Setosa\r\n5.2,3.5,1.5,0.2,Setosa\r\n5.2,3.4,1.4,0.2,Setosa\r\n4.7,3.2,1.6,0.2,Setosa\r\n4.8,3.1,1.6,0.2,Setosa\r\n5.4,3.4,1.5,0.4,Setosa\r\n5.2,4.1,1.5,0.1,Setosa\r\n5.5,4.2,1.4,0.2,Setosa\r\n4.9,3.1,1.5,0.2,Setosa\r\n5,3.2,1.2,0.2,Setosa\r\n5.5,3.

In [31]:
import numpy as np
import pandas as pd

In [32]:
df=pd.read_csv('iris.csv')
df.head(5)

sepal-length  sepal-width  petal-length  petal-width species
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [33]:
X=df.iloc[:,0:4].values
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [34]:
Y=df['species'].values
Y[0:10]

array(['Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Setosa'], dtype=object)

we have already learned how to convert categorical features into numerical ones by using np.where() but now we will label encoder a built in functions to accomplish the same feat

In [35]:
from sklearn.preprocessing import LabelEncoder

The code le=LabelEncoder() creates a new instance of the LabelEncoder class. The LabelEncoder class is a utility class that can be used to encode categorical data into numerical values. This is useful for machine learning models, which typically require numerical data as input.

The code Y=le.fit_transform(Y) encodes the categorical data in the variable Y into numerical values. The fit_transform() method first fits the encoder to the data and then transforms the data.

The code Y[0:10] prints the first 10 rows of the encoded data in the variable Y.

In [36]:
le=LabelEncoder()
Y=le.fit_transform(Y)
Y[0:10]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

The code list(le.classes_) returns a list of the unique categorical values in the data that the LabelEncoder class was fitted to.

In [37]:
list(le.classes_)

['Setosa', 'Versicolor', 'Virginica']

In [38]:
Y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [39]:
from sklearn.preprocessing import StandardScaler

X=sc.fit(X)

This line of code fits the scaler to the data in the variable X. The scaler learns the mean and standard deviation of the data.

X=sc.transform(X)

This line of code transforms the data in the variable X using the fitted scaler. This means that the mean and standard deviation of the transformed data will be 0 and 1, respectively.

X=sc.fit_transform(X)

This line of code is a shortcut for the two lines of code above. It fits the scaler to the data and then transforms the data in a single step.

In [40]:
sc=StandardScaler()
X=sc.fit_transform(X)
X[0:10]

array([[-0.90068117,  1.01900435, -1.34022653, -1.3154443 ],
       [-1.14301691, -0.13197948, -1.34022653, -1.3154443 ],
       [-1.38535265,  0.32841405, -1.39706395, -1.3154443 ],
       [-1.50652052,  0.09821729, -1.2833891 , -1.3154443 ],
       [-1.02184904,  1.24920112, -1.34022653, -1.3154443 ],
       [-0.53717756,  1.93979142, -1.16971425, -1.05217993],
       [-1.50652052,  0.78880759, -1.34022653, -1.18381211],
       [-1.02184904,  0.78880759, -1.2833891 , -1.3154443 ],
       [-1.74885626, -0.36217625, -1.34022653, -1.3154443 ],
       [-1.14301691,  0.09821729, -1.2833891 , -1.44707648]])

In [42]:
from sklearn.model_selection import train_test_split

In [43]:
xtrain,xtest,ytrain,ytest=train_test_split(X,Y,test_size=0.2)

In [45]:
from sklearn.ensemble import RandomForestClassifier
rfc=RandomForestClassifier(n_estimators=20)
rfc.fit(xtrain,ytrain)

RandomForestClassifier(n_estimators=20)

In [46]:
ypred=rfc.predict(xtest)

In [47]:
from sklearn.metrics import confusion_matrix,accuracy_score


In [48]:
ypred

array([0, 2, 2, 0, 0, 1, 0, 2, 0, 2, 0, 1, 0, 2, 0, 1, 1, 1, 1, 1, 2, 2,
       0, 1, 2, 1, 1, 0, 1, 0])

In [49]:
confusion_matrix(ytest,ypred)

array([[11,  0,  0],
       [ 0,  9,  2],
       [ 0,  2,  6]])

In [50]:
accuracy_score(ytest,ypred)

0.8666666666666667